-- Создать и заполнить таблицы лайков и постов.

USE vk

DROP TABLE IF EXISTS likes;

CREATE TABLE likes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  target_id INT UNSIGNED NOT NULL,
  target_type ENUM('messages', 'users', 'posts', 'media') NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS target_types;

CREATE TEMPORARY TABLE target_types (
  name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO target_types (name) VALUES 
  ('messages'),
  ('users'),
  ('media'),
  ('posts');


INSERT INTO likes 
  SELECT 
    id, 
    FLOOR(1 + (RAND() * 100)), 
    FLOOR(1 + (RAND() * 100)),
    (SELECT name FROM target_types ORDER BY RAND() LIMIT 1),
    CURRENT_TIMESTAMP 
  FROM messages;


DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  community_id INT UNSIGNED,
  head VARCHAR(255),
  body TEXT NOT NULL,
  media_id INT UNSIGNED,
  is_public BOOLEAN DEFAULT TRUE,
  is_archived BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


--  http://filldb.info 
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (1, 75, 1, 'id', 'Et architecto et magnam itaque quo omnis nulla reprehenderit. Sed sit alias nihil saepe. In et expedita quis quaerat.', 97, 0, 0, '2018-10-11 22:10:46', '2019-01-27 05:02:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (2, 84, 7, 'pariatur', 'Tempora quo voluptatibus fugit optio repudiandae ipsam dolor aut. Et fugit quia qui adipisci minus recusandae. Animi et non odit dolores cum necessitatibus. Quos quis repellat eaque non rerum.', 49, 1, 0, '2015-09-05 11:16:25', '2018-12-04 03:34:02');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (3, 70, 16, 'et', 'Sunt molestiae harum soluta consequatur quo deleniti. Voluptatem facere molestiae reiciendis ipsam recusandae fugiat eaque.', 91, 1, 0, '2016-03-28 22:07:35', '2015-11-21 22:34:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (4, 75, 26, 'et', 'Ea rerum asperiores voluptas odit nemo. Pariatur at est aut delectus assumenda magnam. Eligendi rem quia quis. Expedita dolores qui eos voluptates.', 38, 0, 1, '2020-12-11 07:10:45', '2019-06-26 02:27:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (5, 26, 2, 'aut', 'Corrupti vel animi cumque occaecati nihil voluptas deleniti. Officia corrupti atque animi reiciendis. Odio quo hic libero qui officiis quis.', 23, 0, 0, '2020-09-17 08:12:26', '2020-01-16 18:27:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (6, 37, 9, 'tenetur', 'Laborum et iste labore blanditiis in ea. Necessitatibus expedita culpa in at iste deleniti. Ex voluptates aut modi placeat harum.', 5, 1, 1, '2012-03-26 23:46:24', '2019-03-14 14:04:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (7, 46, 13, 'explicabo', 'Quia laboriosam sed doloribus perspiciatis repellat. Deleniti modi possimus quo aliquid. Facere doloribus sint voluptas optio libero vitae. Ducimus molestias velit sapiente est.', 71, 1, 1, '2015-04-16 23:32:56', '2012-08-19 01:49:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (8, 31, 19, 'non', 'Temporibus soluta commodi ipsum. Voluptatem a enim quia quaerat. Et aut et deserunt ut. Aut sequi natus est excepturi optio.', 31, 1, 0, '2018-08-03 12:31:32', '2012-07-22 16:40:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (9, 4, 19, 'et', 'Quaerat animi accusamus molestias dolores. Quo odio ducimus ratione in dolor id odit earum. Fugit numquam in voluptate aut.', 88, 0, 1, '2017-04-17 00:54:32', '2013-08-04 06:46:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (10, 18, 12, 'non', 'Ut aperiam ut ea totam aut mollitia. Non est sit incidunt qui non. Minima impedit dolorum ut optio tempora.', 15, 1, 1, '2020-05-29 10:22:23', '2020-10-20 15:01:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (11, 73, 27, 'nemo', 'Maiores distinctio alias porro harum omnis nulla. Perspiciatis tempora cum rem voluptatem nostrum quisquam nisi ut. Perspiciatis dolor repellendus aut consequatur voluptas consectetur velit.', 24, 0, 0, '2016-06-12 12:15:42', '2019-03-07 10:54:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (12, 86, 23, 'sit', 'Aspernatur consequatur facilis nulla nisi labore harum. Quis et voluptas maiores sed corporis quas exercitationem. Dolor quod ea qui consequatur eum iste voluptate. Ipsam nihil quod quisquam qui.', 4, 0, 0, '2014-09-30 10:51:43', '2016-06-09 11:09:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (13, 63, 4, 'ut', 'Officia officia veritatis quia quaerat laboriosam suscipit nobis. Sit sapiente labore aut at et qui mollitia. Tenetur qui dicta doloremque dolor voluptatem. Omnis perferendis quos soluta eum.', 7, 1, 1, '2013-09-21 22:35:24', '2020-03-19 21:07:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (14, 53, 16, 'nulla', 'Aliquam nulla et aut. Autem ut rerum est rem. Quidem omnis quas odit quasi rem.', 38, 1, 0, '2021-01-28 00:42:39', '2015-05-16 23:18:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (15, 33, 14, 'voluptas', 'Nesciunt amet sapiente id consequatur minima. Soluta qui eum deleniti quo.', 38, 0, 1, '2011-11-04 13:56:19', '2017-11-11 15:24:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (16, 62, 13, 'accusamus', 'Error porro quisquam numquam consectetur non corrupti dolorum. Optio harum voluptate ab aut sunt quo numquam possimus. Earum recusandae qui et consequatur.', 88, 0, 1, '2013-02-17 12:31:19', '2016-07-05 01:49:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (17, 77, 6, 'sint', 'Incidunt voluptates quia nisi maxime deleniti. Ut ut ea ut sequi est ut. Labore ducimus reiciendis dignissimos maiores sit sint.', 84, 1, 0, '2012-03-02 01:50:37', '2014-08-28 13:05:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (18, 42, 2, 'fuga', 'Est perferendis molestiae at laborum. Sit quia consequatur aliquid perspiciatis. Ab optio sint autem nobis nulla voluptas atque.', 48, 1, 0, '2018-09-14 16:39:11', '2017-07-22 17:31:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (19, 2, 22, 'sunt', 'Sed saepe eos sed nihil est qui ea. Autem eos aspernatur voluptatum corrupti hic maiores voluptatem. Nemo sed dolores sed dignissimos vitae. Sit rerum ipsum perspiciatis in aut ut esse ut.', 31, 1, 1, '2017-03-24 10:38:01', '2015-06-29 05:32:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (20, 92, 13, 'earum', 'Expedita iste error aut quia totam. Inventore asperiores quis voluptas omnis magnam. Placeat quibusdam est et voluptas et nulla. In ad rerum perspiciatis magnam dolorem corrupti aspernatur.', 10, 0, 1, '2012-12-15 14:04:58', '2011-07-30 23:02:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (21, 3, 16, 'quaerat', 'Omnis ut reprehenderit eos in voluptas ullam. Quam voluptatibus numquam iure maxime ipsum. Ducimus enim inventore facilis et porro.', 6, 1, 0, '2015-09-09 00:45:14', '2018-06-02 12:33:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (22, 88, 16, 'amet', 'Aut consequuntur alias consequatur enim. Necessitatibus odit rerum quia cumque similique laboriosam. Consectetur id aut aut aut natus nam.', 2, 1, 0, '2019-12-14 15:35:51', '2013-07-16 07:53:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (23, 80, 16, 'saepe', 'Esse fugit aut blanditiis non est iste magni. Modi est ut doloribus explicabo. Ipsam dolor quasi et reiciendis quas. Vel excepturi temporibus incidunt sequi.', 21, 0, 1, '2020-08-28 13:54:39', '2018-03-04 10:00:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (24, 80, 29, 'ab', 'Voluptates fugiat incidunt et aut ipsum dolore voluptatibus. Qui distinctio esse soluta. Aut quia qui enim minima libero beatae.', 8, 1, 1, '2015-06-20 09:45:24', '2021-04-10 13:32:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (25, 1, 6, 'deserunt', 'Culpa voluptatem recusandae aspernatur in. Doloremque quasi maxime a provident natus maiores.', 50, 0, 1, '2020-04-28 00:56:59', '2012-09-05 19:08:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (26, 57, 25, 'blanditiis', 'Officia repellendus voluptatem dolorem provident itaque vel. Provident reiciendis ab consectetur consequuntur id.', 49, 0, 1, '2019-10-08 00:55:16', '2013-11-11 20:15:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (27, 72, 7, 'eos', 'Recusandae odio rem incidunt blanditiis. Magnam similique cumque accusantium autem et. Sint tempore dignissimos qui molestiae.', 95, 0, 0, '2015-09-26 15:58:10', '2013-10-01 03:34:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (28, 91, 22, 'exercitationem', 'Laborum sunt molestiae quam quam ex. Enim in ut dicta omnis qui. Voluptatibus repudiandae est unde quisquam quam.', 46, 0, 0, '2014-11-18 01:03:16', '2021-04-14 11:12:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (29, 72, 17, 'explicabo', 'Tenetur est et sequi. Nostrum natus quos eos sint facilis. Tempora qui minus nostrum non aut ut.', 51, 1, 0, '2015-05-12 19:27:44', '2019-10-04 09:38:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (30, 64, 16, 'pariatur', 'Accusamus est praesentium quis exercitationem. Cumque et facilis nostrum consequatur accusamus cumque aliquid. Sed consequatur omnis nihil ducimus autem.', 96, 0, 1, '2018-10-08 15:06:55', '2017-11-18 18:34:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (31, 43, 10, 'cumque', 'Quisquam delectus in earum in dolore. Dicta perferendis rerum dolorum vel fugiat. Et quos vel adipisci deserunt.', 11, 0, 1, '2018-09-10 06:58:57', '2012-12-17 19:48:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (32, 14, 15, 'consequatur', 'Similique libero ipsa aut iusto quas. Totam dolorem non autem.', 19, 1, 0, '2014-12-13 18:37:51', '2015-11-18 22:44:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (33, 3, 29, 'placeat', 'Officia sunt quia error laborum non distinctio quis. Ut et et culpa rerum rem. Et ut rerum molestias et fuga.', 10, 0, 1, '2011-10-20 18:16:51', '2019-08-07 10:04:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (34, 50, 7, 'perspiciatis', 'Unde sed rerum id cumque autem quia. Et explicabo explicabo quae qui. Provident vero odio voluptatum cum culpa optio optio. Sit voluptate placeat occaecati soluta omnis est rerum.', 91, 0, 0, '2017-10-05 08:36:22', '2011-05-16 10:11:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (35, 58, 20, 'debitis', 'Quia magnam assumenda aut. Debitis fugit commodi nam non. Sint animi illo reiciendis laboriosam.', 15, 0, 1, '2015-06-24 20:09:18', '2014-04-10 08:16:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (36, 48, 19, 'perferendis', 'Voluptatum commodi voluptatum consequatur dignissimos sed. Omnis dolorem consectetur et quia temporibus sit. Optio modi pariatur in inventore soluta ab suscipit.', 77, 0, 0, '2019-07-06 21:40:44', '2015-11-02 08:26:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (37, 78, 21, 'provident', 'Vitae rem totam qui voluptas officia. Aut similique eos quia voluptas est incidunt. Soluta natus sunt nam dolore beatae aut temporibus. Hic enim odio voluptatem dolorem tempora omnis omnis.', 23, 0, 0, '2014-03-27 10:10:31', '2020-03-01 02:23:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (38, 61, 14, 'adipisci', 'Quibusdam nisi molestiae labore inventore est quasi. Nisi quo sapiente deserunt dignissimos velit molestias blanditiis. Eligendi vitae quos odio aut voluptate voluptates ab quo. Nam id fugit alias.', 20, 1, 0, '2018-07-25 09:57:04', '2015-06-12 14:51:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (39, 33, 13, 'optio', 'Ut veritatis molestiae perspiciatis. Ut magni aut voluptate saepe. Porro id aut sed illo et et dolor eos. Et doloremque quae sint.', 13, 0, 0, '2012-11-29 06:20:24', '2020-01-18 15:33:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (40, 75, 23, 'debitis', 'Corrupti praesentium vero et. Molestiae qui fuga recusandae qui ullam rem iste. Error dolorem soluta aut reiciendis ut eveniet. Dolore atque incidunt perspiciatis.', 13, 1, 1, '2015-12-24 06:22:42', '2016-12-13 16:40:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (41, 30, 11, 'aut', 'Molestiae aliquam temporibus tenetur reiciendis enim. Aut et nam molestiae nobis corporis asperiores quidem. Officiis laborum ut tenetur at consequatur rerum rem fugit.', 28, 1, 0, '2013-12-11 21:24:53', '2017-10-12 13:48:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (42, 5, 3, 'numquam', 'Enim nihil quibusdam occaecati. Et id ad sapiente voluptas laborum itaque. Iste consequuntur sit praesentium dolor. Corporis voluptas qui non.', 32, 0, 0, '2019-05-01 07:20:21', '2020-01-28 18:50:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (43, 20, 2, 'doloremque', 'Eum voluptas itaque vero rerum itaque. Consequatur ut tenetur odio assumenda. Accusamus quisquam vitae rem facilis accusantium. Doloribus perspiciatis in est quia.', 80, 1, 0, '2016-06-28 11:00:57', '2012-02-04 12:01:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (44, 86, 21, 'ut', 'Vitae est recusandae qui consequatur magni maiores. Aperiam hic non modi sapiente debitis. Et sunt sequi et animi repellendus rem.', 92, 1, 1, '2017-03-15 03:24:24', '2013-10-26 05:01:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (45, 43, 17, 'quas', 'Quae non vitae fugiat labore. Temporibus vero quo eius. Ullam delectus dolorem nostrum. Ut exercitationem eaque debitis qui autem.', 44, 1, 0, '2017-09-12 00:14:20', '2012-08-27 19:53:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (46, 84, 16, 'omnis', 'Veniam fuga perferendis fugiat est fuga ea nulla delectus. Facere nihil veniam omnis. Quia facilis nihil in odio possimus quos. Excepturi deserunt dolorum eveniet illo reiciendis.', 32, 0, 1, '2020-10-04 05:55:44', '2021-01-20 16:58:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (47, 24, 5, 'minus', 'Incidunt officiis error exercitationem nisi dolores voluptate. Et suscipit et nam voluptatem consequatur sit. Voluptatum voluptatem et doloribus aut ut aut fuga.', 79, 1, 0, '2017-12-20 12:33:42', '2019-06-12 17:00:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (48, 14, 15, 'libero', 'Iusto qui vel aut culpa dolores. Exercitationem voluptas voluptas ut laborum rerum quibusdam assumenda. Voluptatum ullam harum et laboriosam. Consequuntur nesciunt voluptas unde at et.', 12, 0, 0, '2014-05-25 23:47:08', '2016-02-18 22:53:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (49, 27, 11, 'qui', 'Nulla nihil dolor iste est illo rem. Mollitia eos enim iste dicta. Ab excepturi quia nisi.', 46, 1, 1, '2015-07-15 17:42:49', '2014-06-29 18:33:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (50, 97, 26, 'vitae', 'Inventore qui voluptatibus dignissimos repudiandae. Ex molestiae in quia odio natus illo ut. Occaecati commodi nihil rem quam dolores. Autem quia ea dolorem.', 18, 1, 1, '2018-11-05 12:59:20', '2017-03-28 19:30:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (51, 78, 10, 'esse', 'Quasi eum provident accusantium similique dolor voluptas. Voluptatem optio voluptatum a fugit dolores nesciunt nam. Consequatur optio ut minus porro. Iure corporis facilis ratione nostrum ea.', 76, 0, 0, '2014-07-03 18:13:28', '2017-06-07 01:05:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (52, 96, 26, 'enim', 'Rerum porro ex est est laudantium. Doloribus nam ratione nulla voluptates. Nemo minus non ut quo eos ducimus doloribus. Architecto ex non in quia vel.', 12, 1, 1, '2013-07-23 01:09:34', '2020-03-30 19:53:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (53, 31, 5, 'laudantium', 'Aspernatur laboriosam sunt saepe dolor velit consequatur qui suscipit. Animi sint voluptatem neque earum facere sequi illum voluptas. Quia fugit adipisci at et voluptas.', 51, 1, 0, '2017-01-03 20:06:59', '2014-02-26 09:47:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (54, 50, 18, 'omnis', 'Sit iste tempore distinctio. Ad harum ducimus est est architecto. Doloremque quisquam et architecto non natus non ut.', 17, 0, 1, '2013-11-23 23:32:06', '2017-01-30 10:31:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (55, 42, 1, 'vel', 'Aut id quo odio rerum quia. Tempora veniam debitis in reiciendis consectetur. Impedit asperiores omnis corporis repudiandae quo voluptatem.', 66, 1, 1, '2011-11-11 17:52:51', '2014-06-16 18:09:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (56, 62, 27, 'pariatur', 'Pariatur necessitatibus sunt eaque explicabo quas molestiae quibusdam. Consequatur esse molestias est molestias. Sunt quo consequatur tempora odio.', 26, 1, 1, '2017-08-26 11:25:28', '2020-09-30 11:19:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (57, 68, 26, 'eos', 'Libero possimus aspernatur mollitia commodi consequatur eaque. Autem recusandae voluptatum odio enim ipsa ut laboriosam. Eum odio sunt sint rerum laboriosam.', 26, 1, 1, '2013-11-12 06:00:56', '2015-11-22 09:48:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (58, 39, 4, 'molestias', 'Ex accusamus natus ipsam. Omnis asperiores nulla sint ducimus. Totam minima occaecati voluptas.', 12, 1, 1, '2018-06-15 07:58:24', '2020-07-26 15:01:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (59, 65, 27, 'aperiam', 'Non dignissimos et placeat ratione iusto et. Cum sapiente laborum aliquid iusto ipsam reprehenderit. Vitae aliquam necessitatibus pariatur eos praesentium voluptatem et quia.', 60, 1, 0, '2017-12-11 07:51:22', '2020-01-19 09:49:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (60, 22, 14, 'incidunt', 'Enim et quis voluptas sit cumque. Consequatur et eum aut. Nisi non totam eius qui.', 93, 1, 1, '2017-02-22 07:14:50', '2013-11-06 15:33:50');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (61, 9, 16, 'libero', 'Porro aperiam error et nemo a. Libero cupiditate et nihil laborum fugit sunt. Distinctio fugiat rerum et sint quaerat consequatur.', 90, 0, 1, '2017-08-08 11:28:00', '2020-03-26 06:36:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (62, 45, 25, 'et', 'Veniam repudiandae quia eveniet porro maiores possimus. Non doloribus sunt rerum deleniti. Architecto consequuntur voluptatem et similique aut quo.', 58, 0, 0, '2013-04-26 15:46:03', '2015-10-19 13:22:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (63, 14, 20, 'magnam', 'Ullam non modi aut sunt rerum. Mollitia ut et eaque quis minus vel.', 27, 0, 1, '2016-05-05 16:59:31', '2012-09-03 14:48:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (64, 4, 17, 'modi', 'Et unde consequuntur aliquid tempore reiciendis. Beatae est nihil explicabo nisi libero explicabo labore. Corrupti alias voluptas et et corrupti enim.', 66, 1, 0, '2013-08-08 12:21:04', '2014-12-23 02:50:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (65, 13, 14, 'rerum', 'Alias fugit dolorem et quia. Assumenda cupiditate totam fugiat est. Vel et omnis aut dolorum.', 59, 0, 1, '2017-07-25 17:07:08', '2016-09-28 23:23:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (66, 15, 15, 'vero', 'Ea dolorum dolorem ut. Nam illum tempore aut quo debitis nihil quod. Deserunt sint quos quis minus. Voluptatem omnis eum molestiae omnis laborum molestias.', 74, 0, 1, '2014-11-29 23:01:38', '2020-02-02 16:13:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (67, 5, 19, 'aut', 'Omnis placeat at qui dolorem. Veniam qui esse nostrum beatae quia. Iste maxime enim ex voluptas. Rerum dolores sequi occaecati nisi consequatur.', 2, 0, 0, '2014-08-26 01:32:43', '2019-07-01 11:37:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (68, 70, 2, 'amet', 'Cumque aut est aut est numquam. Voluptas qui voluptas neque aut eius numquam accusantium. Deserunt reprehenderit qui officia iste.', 96, 0, 1, '2015-04-24 12:28:50', '2017-10-23 01:04:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (69, 10, 3, 'quod', 'Quas sint quos qui illum optio. Officiis corporis minus aspernatur qui totam. Est quos aut velit nesciunt fuga cupiditate. Vel doloribus quia dolore ipsa explicabo ex.', 50, 1, 0, '2012-07-13 09:31:39', '2011-05-24 08:37:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (70, 15, 7, 'voluptatum', 'Quas quia alias doloribus est facilis reiciendis et. Est sunt non minus ut odio quam et.\nNobis provident qui rerum qui. Iste consequuntur qui eos ut. Quia quae quibusdam beatae minima est quidem.', 47, 0, 0, '2014-06-14 19:24:44', '2014-10-13 02:44:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (71, 48, 30, 'harum', 'Voluptatum illo eos et culpa exercitationem at. Esse impedit autem quos nostrum aut quo. Eveniet sequi autem non ut voluptas aut eveniet. Rerum ex qui dolor alias.', 30, 1, 1, '2016-03-24 14:53:47', '2016-07-20 11:34:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (72, 27, 11, 'nisi', 'Nemo in assumenda accusantium numquam quas nesciunt. Assumenda ducimus et cumque aut esse aliquam. Et qui doloribus excepturi nisi. Quis adipisci alias vitae. Numquam sed dolorum distinctio.', 74, 1, 1, '2014-06-25 20:50:02', '2020-11-15 04:06:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (73, 34, 6, 'cupiditate', 'Sequi vero ratione qui quia molestiae. Eum iste ipsum deleniti nihil omnis. Consequuntur quia adipisci reiciendis. Modi est fugit omnis dolorum veritatis tenetur.', 36, 1, 1, '2020-05-02 15:03:11', '2020-07-17 19:17:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (74, 50, 19, 'iusto', 'Eum cumque voluptatem unde quos esse. Aut sit aperiam sint quos aut est. Alias iste qui labore ut nam dolore dolore velit. Esse voluptatibus voluptates amet nulla debitis.', 100, 1, 1, '2017-04-10 16:09:15', '2012-01-29 03:30:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (75, 70, 18, 'et', 'Voluptatum recusandae officiis similique nobis facilis sunt enim. Aut est ea corrupti vel ullam sunt.', 99, 1, 1, '2019-08-29 05:31:19', '2013-01-06 08:21:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (76, 92, 3, 'qui', 'Modi cupiditate enim exercitationem. At quidem voluptas nulla a iusto placeat sunt.', 8, 1, 0, '2019-08-26 20:34:13', '2013-10-10 12:19:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (77, 12, 11, 'numquam', 'Facere assumenda rerum velit. Quisquam quia sunt recusandae eaque et reiciendis. Non ut tempora laboriosam qui. Quo est omnis sit et pariatur doloribus.', 63, 1, 0, '2016-06-14 21:19:10', '2014-03-29 12:31:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (78, 21, 13, 'sequi', 'At sunt voluptas sunt adipisci aperiam nihil. Molestias temporibus quia odit reprehenderit ab omnis. Nobis eum voluptatibus voluptas iure. Inventore illum odit et aut earum consequatur rerum.', 48, 0, 1, '2012-06-02 17:29:42', '2020-08-20 04:00:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (79, 82, 2, 'voluptas', 'Quis aut et quos quas. Voluptatem eveniet vero quo et autem exercitationem adipisci. Quasi soluta aliquid temporibus voluptatem adipisci ullam minus.', 22, 0, 1, '2020-10-29 12:28:17', '2015-02-05 17:23:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (80, 65, 6, 'ut', 'Sed qui est necessitatibus rem qui necessitatibus rerum. Necessitatibus facere dignissimos similique corporis ut.', 16, 0, 1, '2012-06-28 02:16:48', '2018-07-10 10:46:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (81, 52, 30, 'sint', 'Sed a ipsam explicabo exercitationem tenetur. Eveniet quos fugit aut dolor cupiditate praesentium. Quam ratione quibusdam maxime sit in nostrum.', 50, 1, 1, '2019-08-18 12:14:52', '2017-07-17 00:08:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (82, 4, 27, 'numquam', 'Voluptatem libero et dolor provident ad. Architecto corporis et eos. Aut est nisi quo sapiente eos sit.\nAliquam nostrum iste porro cumque voluptatem mollitia. Explicabo praesentium molestiae error.', 80, 1, 0, '2020-04-10 12:11:59', '2011-07-28 11:42:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (83, 29, 15, 'et', 'Error suscipit culpa et sed et est blanditiis. Laudantium rerum fuga a voluptas. Blanditiis culpa molestiae soluta consequuntur eum. Id illo rerum numquam et.', 62, 1, 0, '2012-10-28 08:58:09', '2013-07-06 17:18:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (84, 19, 24, 'non', 'Soluta culpa sit et magni. Expedita minima voluptatum eum libero quia maxime. Quis nostrum at maxime natus non repellendus.', 53, 0, 1, '2017-11-13 14:10:20', '2017-01-12 21:26:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (85, 10, 14, 'et', 'Quo amet consequatur ipsum qui. Ab officia aspernatur cupiditate magni sapiente. Voluptas commodi aliquid aut magnam.', 30, 0, 0, '2018-07-01 03:12:46', '2016-12-21 01:18:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (86, 14, 23, 'corporis', 'Harum necessitatibus qui non. Odit ipsa quia ut ut porro mollitia. Assumenda animi similique ab. Repellat recusandae cum sunt et fuga unde deserunt.', 28, 1, 0, '2015-03-12 14:21:01', '2012-05-22 01:16:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (87, 68, 21, 'sit', 'Recusandae alias occaecati repellendus iusto fuga. Eius ut earum sint sunt et ut ut.', 99, 0, 0, '2012-11-16 08:14:32', '2015-04-04 09:46:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (88, 96, 10, 'cum', 'Atque cupiditate facere assumenda incidunt aut. Pariatur et vel vero molestias. Non ipsam vel totam amet est nihil eos eum.', 84, 1, 0, '2020-06-15 05:48:44', '2011-06-25 09:32:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (89, 97, 25, 'rerum', 'Quia dolorem alias provident. Dolor aut aliquid natus. Quam omnis quia ut quis ab. Et recusandae hic dolor quia assumenda.', 75, 1, 0, '2013-01-21 23:48:45', '2014-12-07 16:14:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (90, 12, 18, 'quo', 'Quam eos enim sint sit assumenda. Natus optio veniam eaque dolores modi sit quos. Unde eveniet quo ut ut similique molestiae et. Sequi cumque quaerat ut fuga totam itaque.', 20, 1, 1, '2011-11-12 13:18:59', '2020-07-05 02:29:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (91, 98, 29, 'facilis', 'Qui et praesentium quae alias eveniet sapiente deserunt. Voluptates consequatur voluptas magnam. Aut alias aliquam nobis nihil.', 67, 0, 1, '2015-09-15 09:18:43', '2015-07-05 20:25:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (92, 76, 5, 'ea', 'Ut dolor culpa error. Labore velit ducimus in voluptas nobis. Ratione velit iste dignissimos ducimus. Rerum enim nisi sunt esse.', 1, 0, 0, '2012-11-19 23:15:46', '2018-07-30 03:24:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (93, 13, 11, 'ab', 'Fuga earum rerum eveniet perspiciatis deleniti. Amet autem recusandae voluptatem illo.', 81, 0, 1, '2015-08-13 17:45:22', '2014-08-06 09:03:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (94, 79, 30, 'ipsa', 'Et ut ipsa voluptatibus nihil aut perferendis non. Est sit sint velit adipisci vitae non. Consequuntur nihil odio quia voluptates earum est impedit.', 57, 1, 0, '2013-04-05 17:07:47', '2014-11-24 05:25:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (95, 62, 19, 'sunt', 'Reiciendis recusandae rem eos hic. Praesentium unde quisquam non et ut officia deserunt.', 10, 1, 1, '2011-08-11 04:15:35', '2011-09-25 19:36:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (96, 64, 24, 'ad', 'Laboriosam voluptate qui saepe in. Vel autem nobis laboriosam delectus animi est iste. Magni quia et odio qui et cumque architecto.', 91, 0, 0, '2021-03-09 16:59:40', '2014-09-14 09:42:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (97, 21, 11, 'voluptas', 'Reprehenderit nemo nihil iure magnam doloribus labore alias qui. Expedita aut velit veniam eligendi natus cum voluptate. Autem iste eveniet sit et magnam et. Aut dicta qui et enim sit reprehenderit.', 18, 0, 0, '2019-10-26 19:15:01', '2017-03-17 08:32:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (98, 86, 22, 'nostrum', 'Voluptatem repellendus cupiditate delectus culpa. Qui est repellendus aut eveniet sint quo occaecati omnis. Nemo et quisquam quisquam perspiciatis in necessitatibus ut.', 16, 1, 1, '2019-03-17 18:49:55', '2014-09-12 07:10:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (99, 55, 7, 'nam', 'Officiis consectetur nihil velit vel qui tenetur hic. Ea iusto velit rerum sunt libero. Repudiandae iure velit quis quos blanditiis.', 65, 0, 0, '2015-07-09 16:01:17', '2012-01-03 05:31:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (100, 40, 4, 'ab', 'Quod similique pariatur molestiae. Rerum amet vitae illo repellendus ab. Temporibus accusamus eum esse natus vitae.', 31, 1, 0, '2014-11-29 19:41:50', '2016-03-19 02:15:48');


